### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai-191-kucheruk#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
8) Поясніть, будь ласка, різницю у безпечності операцій доступу (читання, редагування) 
GitHub-репозиторія на основі мережевого протоколу HTTPS та 
на основі протоколу SSH як мережевого протокола рівня застосунків.

**Comment by VladislavDDP** [comment]
@oleksandrblazhko HTTPS і SSH - це два різних протоколи за допомогою яких можна отримати доступ до репозиторіїв на GitHub або інших системах керування версіями. Основні відмінності у безпеці операцій доступу наведу нижче:

**HTTPS:**

- При використанні HTTPS ваші дані (включаючи імена користувачів та паролі) шифруються, що робить їх менш доступними для перехоплення під час передачі через мережу.

- Для доступу до репозиторію через HTTPS, зазвичай вам потрібно ввести свій логін і пароль GitHub при кожному доступі або використовувати токен доступу.

**SSH:**

- При використанні SSH ви генеруєте ключі SSH (приватний та публічний). Приватний ключ залишається на вашому комп'ютері, а публічний ключ додається до вашого облікового запису GitHub.

- SSH використовує ключі для аутентифікації, і ви не повинні вводити пароль кожного разу, коли працюєте з репозиторієм. Це робить процес більш безпечним, оскільки ключі важко вгадати або перехопити.

Основна різниця полягає в тому, що HTTPS вимагає введення логіна та пароля (або використання токена доступу) при кожному доступі, і дані передаються в зашифрованому вигляді, тоді як SSH використовує ключі для аутентифікації і не вимагає постійного введення паролю. SSH вважається більш безпечним, але вимагає створення та керування ключами.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
